name: jacobi_task_env
channels:
  - conda-forge
dependencies:
  - python=3.10.18
  - pip=25.2
  - numpy=1.26.4
  - scipy=1.15.3
  - matplotlib=3.10.5
  - open3d=0.19.0
  - pip:
      - meshcat
      - meshcat-shapes==1.0.0

